language: node_js
node_js:
- '6'
- '4'
- '0.12'
deploy:
  on:
    branch: master
    tags: true
  provider: npm
  email: "richie.mackay@gmail.com"
  api_key:
    secure: DZjNCYSlFxo99MJ+q57/Bk68JzszbA+E6JulBQBiTJngZtbKAQjGhqgZQ7Xn5t6UFttifaIPGEO56wLmTyZ3ezGR5hCcSO1ufhjjGIMhwkS1VFQMQER28qU/GMUBay2rKSGtB1KikXzFUNXxVk+mBg/vY8QnhGEoKBFKS5zvRsJU6rbDimFGWdS9iEwkb3Lbmv5F35gLjdtmy67Ld/0ipLnwjVd2CvzFatxUaesxMRDFScOsZRlMzxQZJdcs8OjGzLxt8wzU4zshptFi0MatQ81jCIuJd6saSujxos5ANgPQzREK1WWLPoJ5qvtQExJ2V9hC0s0W6bNTsnsqfkRptv5RL/C4CJQ/HJzeSt2umecHnW+PEkeEMy3wihO36KaS4xgV+DCdp9vhmxAncz9TuNZh0vWbC3vwY2dzlJpJ7s4CypywZkkdZr/1NDJL3Zvh5E97ytyWvOcnMJRJ04IrXef88LUKLXdLS2CB7mGqv+wO/RCpeKUKbrnNDmYCMZ3C+mHBVDbrmjUJoOSFxOJ1MyQGxx5dKUzM95iGcJz8QSl8rMJXWB2fgosLc3fvlR11SlGH8DXLCkpHd12fIDJq+CfQZPE4qQ8SZMno/JHJpQTFSCBlX4PXI5XUj7JbhLMzOsdY7CteuX0bY0d936BEsaMN30g2VNzLi74XH16W/sk=
